  services:
    database:
      build: .
      ports: 
        - 50000:50000
      environment:
        DB_FARM: "/var/monetdb5/dbfarm"
        DB_NAME: "vesselai_db"
        DB_USER: "vesselai_user"
        DB_PASSWORD: "vesselai_pass"
      volumes:
        - database_storage:/var/monetdb5/dbfarm
        - type: bind
          source: ./
          target: /initdb/
  volumes:
    database_storage:

